name: Go

on:
  push:
    branches: [ main ]
    tags:
      - v*.*

  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: |
        go build -ldflags "-s -w" .

    - name: Build Desktop AppImage
      run: |
        # install some build time dependencies
        sudo apt-get -qy install libwebkit2gtk-4.0-dev  build-essential libgtk-3-dev
        cd cmd/desktop
        go build -ldflags "-s -w" .
        cp AppDir squashfs-root -r
        cp ./desktop squashfs-root/lyrix-desktop
        cp templates static squashfs-root/. -r
        wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool*.AppImage
        ./appimagetool*.AppImage squashfs-root
        cd ../..

    - name: Release
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        wget https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
        chmod +x pyuploadtool-x86_64.AppImage
        ./pyuploadtool-x86_64.AppImage lyrixd cmd/desktop/Lyrix*.AppImage


